#!/bin/sh

export ponto='/home/manjaro-cm/.functions_file'

source $ponto/01-modify-speed-of-the-videos
source $ponto/02-music
source $ponto/03-project-music-in-terminal
source $ponto/04-calculator
source $ponto/05-cut-pdf
source $ponto/06-merger-of-pdfs
source $ponto/07-download-youtube-musics
source $ponto/08-extract-file
source $ponto/09-function-to-open-files








source $ponto/16-rename-all-file
source $ponto/17-color-example

