#!/bin/sh

aumentar() {
    arquivo=$(echo "$2" | cut -d '.' -f1)
    ffmpeg -i $2 -filter_complex "[0:v]setpts=PTS/$1[v];[0:a]atempo=$1[a]" -map "[v]" -map "[a]" $arquivo-$1.mp4
    echo -n "Aguarde, estamos finalizando"
    for _ in {1..3}; do
        echo -n "."; sleep .5
    done; echo ''
    while [ true ]; do
        echo -n "Deseja excluir o arquivo: $2 [S/n]? "; read mc
        if [ "$mc" = "S" ]; then
            rm $2
            break
        elif [ "$mc" = "n" ]; then
            break
        fi
    done
}

