#!/bin/sh

aumentarr() {
	arquivo=$(echo "$2" | cut -d '.' -f1)
	ffmpeg -i $2 -filter_complex "[0:v]setpts=PTS/$1[v];[0:a]atempo=$1[a]" -map "[v]" -map "[a]" $arquivo-$1.mp4
	echo -n "Aguarde, estamos finalizando"
	sleep 0.2
	echo -n " ."
	sleep 0.2
	echo -n " ."
	sleep 0.2
	echo " ."
	echo "\033[32mFinalizado.\033[m"
	while [ true ]; do
		echo -n "Deseja excluir o arquivo:\033[36m $2\033[m [S/n]? "; read mc
		if [ "$mc" = "S" ]; then
			rm $2
			break
		elif [ "$mc" = "n" ]; then
			break
		fi
	done
}

